server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.149.17:3306/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: ws-123456

  redis:
    host: 192.168.149.17
    password: unity2.0@wondersoft
    port: 6379
    jedis:
      pool:
        enabled: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: is_removed
      logic-delete-value: 1
      logic-not-delete-value: 0
